### ISSUE TITLE
@Keyframs move  SyntaxError: Invalid or unexpected token in using react-block-reveal-animation React + Next.js

### ISSUE THREAD

**Issue by JaySheth51** [pettersamuelsen/react-block-reveal-animation#1]
Invalid or unexpected token
E:\Projects\nextjs\ Website\node_modules\react-block-reveal-animation\dist\BlockRevealAnimation.css:1 (function (exports, require, module, __filename, __dirname) { 
                                                            @keyframes move {
                                                              ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Projects\nextjs\Website\node_modules\react-block-reveal-animation\dist\BlockRevealAnimation.js:15:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)

`import React from 'react';
import BlockRevealAnimation from 'react-block-reveal-animation';
const BlockReveal = () => (
    <BlockRevealAnimation>
        <div id="rev-6 Tilt-inner" >
            <Fade left>
                <img src="static/images/dew-ban.jpg" alt="dew-ban" data-tilt />
            </Fade>
        </div>
    </BlockRevealAnimation>
)`

**Comment by pettersamuelsen** [comment]
This sounds like a webpack/next.js related issue. Are you using the css-loader for webpack?

https://github.com/zeit/next.js/issues/3408

**Comment by JaySheth51** [comment]
Yes i have used [next-css](https://github.com/zeit/next-plugins/tree/master/packages/next-css). and also added this too.
// next.config.js
const withCSS = require('@zeit/next-css')
module.exports = withCSS()

**Comment by seolargo** [comment]
I got the same issue. Were you able to solve this problem?
